server:
    port: 8080
    servlet:
        context-path: /desafio-sebrae

spring:
    datasource:
        url: jdbc:h2:mem:desafio-sebrae
        username: sa
        password:
        driverClassName: org.h2.Driver
    
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    
    h2:
        console.enabled: true
    
    liquibase:
        enabled: true
        change-log: classpath:db/master.xml
        default-schema: public